import { Box, Button, Typography } from '@mui/material';
import React from 'react';
import AppAutoComplete from '../../../components/common/AppAutoComplete';




export default function UserList() {

    const onSelectAutoComplete = (value) => {
        // console(value.label);
    }

    return (
        
            <Box xs={{display: 'flex'}}>
            <AppAutoComplete size="small" label="Select Country" allowIcons={true} data={countries} onSelect={onSelectAutoComplete} />
            <AppAutoComplete size="small" label="Organisation" allowIcons={false} data={organisations} onSelect={onSelectAutoComplete} />
            </Box>
        
    )
}


const organisations = [
    {id: 'ORG', title: "Maliyat", phone: "000"},
    {id: 'ORG', title: "GSB", phone: "002"},
]

const countries = [
  { id: 'AD', title: 'Andorra', phone: '376' },
  {
    id: 'AE',
    title: 'United Arab Emirates',
    phone: '971',
  },
  { id: 'AF', title: 'Afghanistan', phone: '93' },
  {
    id: 'AG',
    title: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { id: 'AI', title: 'Anguilla', phone: '1-264' },
  { id: 'AL', title: 'Albania', phone: '355' },
  { id: 'AM', title: 'Armenia', phone: '374' },
  { id: 'AO', title: 'Angola', phone: '244' },
  { id: 'AQ', title: 'Antarctica', phone: '672' },
  { id: 'AR', title: 'Argentina', phone: '54' },
  { id: 'AS', title: 'American Samoa', phone: '1-684' },
  { id: 'AT', title: 'Austria', phone: '43' },
  {
    id: 'AU',
    title: 'Australia',
    phone: '61',
    suggested: true,
  },
  { id: 'AW', title: 'Aruba', phone: '297' },
  { id: 'AX', title: 'Alland Islands', phone: '358' },
  { id: 'AZ', title: 'Azerbaijan', phone: '994' },
  {
    id: 'BA',
    title: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { id: 'BB', title: 'Barbados', phone: '1-246' },
  { id: 'BD', title: 'Bangladesh', phone: '880' },
  { id: 'BE', title: 'Belgium', phone: '32' },
  { id: 'BF', title: 'Burkina Faso', phone: '226' },
  { id: 'BG', title: 'Bulgaria', phone: '359' },
  { id: 'BH', title: 'Bahrain', phone: '973' },
  { id: 'BI', title: 'Burundi', phone: '257' },
  { id: 'BJ', title: 'Benin', phone: '229' },
  { id: 'BL', title: 'Saint Barthelemy', phone: '590' },
  { id: 'BM', title: 'Bermuda', phone: '1-441' },
  { id: 'BN', title: 'Brunei Darussalam', phone: '673' },
  { id: 'BO', title: 'Bolivia', phone: '591' },
  { id: 'BR', title: 'Brazil', phone: '55' },
  { id: 'BS', title: 'Bahamas', phone: '1-242' },
  { id: 'BT', title: 'Bhutan', phone: '975' },
  { id: 'BV', title: 'Bouvet Island', phone: '47' },
  { id: 'BW', title: 'Botswana', phone: '267' },
  { id: 'BY', title: 'Belarus', phone: '375' },
  { id: 'BZ', title: 'Belize', phone: '501' },
  {
    id: 'CA',
    title: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    id: 'CC',
    title: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    id: 'CD',
    title: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    id: 'CF',
    title: 'Central African Republic',
    phone: '236',
  },
  {
    id: 'CG',
    title: 'Congo, Republic of the',
    phone: '242',
  },
  { id: 'CH', title: 'Switzerland', phone: '41' },
  { id: 'CI', title: "Cote d'Ivoire", phone: '225' },
  { id: 'CK', title: 'Cook Islands', phone: '682' },
  { id: 'CL', title: 'Chile', phone: '56' },
  { id: 'CM', title: 'Cameroon', phone: '237' },
  { id: 'CN', title: 'China', phone: '86' },
  { id: 'CO', title: 'Colombia', phone: '57' },
  { id: 'CR', title: 'Costa Rica', phone: '506' },
  { id: 'CU', title: 'Cuba', phone: '53' },
  { id: 'CV', title: 'Cape Verde', phone: '238' },
  { id: 'CW', title: 'Curacao', phone: '599' },
  { id: 'CX', title: 'Christmas Island', phone: '61' },
  { id: 'CY', title: 'Cyprus', phone: '357' },
  { id: 'CZ', title: 'Czech Republic', phone: '420' },
  {
    id: 'DE',
    title: 'Germany',
    phone: '49',
    suggested: true,
  },
  { id: 'DJ', title: 'Djibouti', phone: '253' },
  { id: 'DK', title: 'Denmark', phone: '45' },
  { id: 'DM', title: 'Dominica', phone: '1-767' },
  {
    id: 'DO',
    title: 'Dominican Republic',
    phone: '1-809',
  },
  { id: 'DZ', title: 'Algeria', phone: '213' },
  { id: 'EC', title: 'Ecuador', phone: '593' },
  { id: 'EE', title: 'Estonia', phone: '372' },
  { id: 'EG', title: 'Egypt', phone: '20' },
  { id: 'EH', title: 'Western Sahara', phone: '212' },
  { id: 'ER', title: 'Eritrea', phone: '291' },
  { id: 'ES', title: 'Spain', phone: '34' },
  { id: 'ET', title: 'Ethiopia', phone: '251' },
  { id: 'FI', title: 'Finland', phone: '358' },
  { id: 'FJ', title: 'Fiji', phone: '679' },
  {
    id: 'FK',
    title: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    id: 'FM',
    title: 'Micronesia, Federated States of',
    phone: '691',
  },
  { id: 'FO', title: 'Faroe Islands', phone: '298' },
  {
    id: 'FR',
    title: 'France',
    phone: '33',
    suggested: true,
  },
  { id: 'GA', title: 'Gabon', phone: '241' },
  { id: 'GB', title: 'United Kingdom', phone: '44' },
  { id: 'GD', title: 'Grenada', phone: '1-473' },
  { id: 'GE', title: 'Georgia', phone: '995' },
  { id: 'GF', title: 'French Guiana', phone: '594' },
  { id: 'GG', title: 'Guernsey', phone: '44' },
  { id: 'GH', title: 'Ghana', phone: '233' },
  { id: 'GI', title: 'Gibraltar', phone: '350' },
  { id: 'GL', title: 'Greenland', phone: '299' },
  { id: 'GM', title: 'Gambia', phone: '220' },
  { id: 'GN', title: 'Guinea', phone: '224' },
  { id: 'GP', title: 'Guadeloupe', phone: '590' },
  { id: 'GQ', title: 'Equatorial Guinea', phone: '240' },
  { id: 'GR', title: 'Greece', phone: '30' },
  {
    id: 'GS',
    title: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { id: 'GT', title: 'Guatemala', phone: '502' },
  { id: 'GU', title: 'Guam', phone: '1-671' },
  { id: 'GW', title: 'Guinea-Bissau', phone: '245' },
  { id: 'GY', title: 'Guyana', phone: '592' },
  { id: 'HK', title: 'Hong Kong', phone: '852' },
  {
    id: 'HM',
    title: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { id: 'HN', title: 'Honduras', phone: '504' },
  { id: 'HR', title: 'Croatia', phone: '385' },
  { id: 'HT', title: 'Haiti', phone: '509' },
  { id: 'HU', title: 'Hungary', phone: '36' },
  { id: 'ID', title: 'Indonesia', phone: '62' },
  { id: 'IE', title: 'Ireland', phone: '353' },
  { id: 'IL', title: 'Israel', phone: '972' },
  { id: 'IM', title: 'Isle of Man', phone: '44' },
  { id: 'IN', title: 'India', phone: '91' },
  {
    id: 'IO',
    title: 'British Indian Ocean Territory',
    phone: '246',
  },
  { id: 'IQ', title: 'Iraq', phone: '964' },
  {
    id: 'IR',
    title: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { id: 'IS', title: 'Iceland', phone: '354' },
  { id: 'IT', title: 'Italy', phone: '39' },
  { id: 'JE', title: 'Jersey', phone: '44' },
  { id: 'JM', title: 'Jamaica', phone: '1-876' },
  { id: 'JO', title: 'Jordan', phone: '962' },
  {
    id: 'JP',
    title: 'Japan',
    phone: '81',
    suggested: true,
  },
  { id: 'KE', title: 'Kenya', phone: '254' },
  { id: 'KG', title: 'Kyrgyzstan', phone: '996' },
  { id: 'KH', title: 'Cambodia', phone: '855' },
  { id: 'KI', title: 'Kiribati', phone: '686' },
  { id: 'KM', title: 'Comoros', phone: '269' },
  {
    id: 'KN',
    title: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    id: 'KP',
    title: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { id: 'KR', title: 'Korea, Republic of', phone: '82' },
  { id: 'KW', title: 'Kuwait', phone: '965' },
  { id: 'KY', title: 'Cayman Islands', phone: '1-345' },
  { id: 'KZ', title: 'Kazakhstan', phone: '7' },
  {
    id: 'LA',
    title: "Lao People's Democratic Republic",
    phone: '856',
  },
  { id: 'LB', title: 'Lebanon', phone: '961' },
  { id: 'LC', title: 'Saint Lucia', phone: '1-758' },
  { id: 'LI', title: 'Liechtenstein', phone: '423' },
  { id: 'LK', title: 'Sri Lanka', phone: '94' },
  { id: 'LR', title: 'Liberia', phone: '231' },
  { id: 'LS', title: 'Lesotho', phone: '266' },
  { id: 'LT', title: 'Lithuania', phone: '370' },
  { id: 'LU', title: 'Luxembourg', phone: '352' },
  { id: 'LV', title: 'Latvia', phone: '371' },
  { id: 'LY', title: 'Libya', phone: '218' },
  { id: 'MA', title: 'Morocco', phone: '212' },
  { id: 'MC', title: 'Monaco', phone: '377' },
  {
    id: 'MD',
    title: 'Moldova, Republic of',
    phone: '373',
  },
  { id: 'ME', title: 'Montenegro', phone: '382' },
  {
    id: 'MF',
    title: 'Saint Martin (French part)',
    phone: '590',
  },
  { id: 'MG', title: 'Madagascar', phone: '261' },
  { id: 'MH', title: 'Marshall Islands', phone: '692' },
  {
    id: 'MK',
    title: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { id: 'ML', title: 'Mali', phone: '223' },
  { id: 'MM', title: 'Myanmar', phone: '95' },
  { id: 'MN', title: 'Mongolia', phone: '976' },
  { id: 'MO', title: 'Macao', phone: '853' },
  {
    id: 'MP',
    title: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { id: 'MQ', title: 'Martinique', phone: '596' },
  { id: 'MR', title: 'Mauritania', phone: '222' },
  { id: 'MS', title: 'Montserrat', phone: '1-664' },
  { id: 'MT', title: 'Malta', phone: '356' },
  { id: 'MU', title: 'Mauritius', phone: '230' },
  { id: 'MV', title: 'Maldives', phone: '960' },
  { id: 'MW', title: 'Malawi', phone: '265' },
  { id: 'MX', title: 'Mexico', phone: '52' },
  { id: 'MY', title: 'Malaysia', phone: '60' },
  { id: 'MZ', title: 'Mozambique', phone: '258' },
  { id: 'NA', title: 'Namibia', phone: '264' },
  { id: 'NC', title: 'New Caledonia', phone: '687' },
  { id: 'NE', title: 'Niger', phone: '227' },
  { id: 'NF', title: 'Norfolk Island', phone: '672' },
  { id: 'NG', title: 'Nigeria', phone: '234' },
  { id: 'NI', title: 'Nicaragua', phone: '505' },
  { id: 'NL', title: 'Netherlands', phone: '31' },
  { id: 'NO', title: 'Norway', phone: '47' },
  { id: 'NP', title: 'Nepal', phone: '977' },
  { id: 'NR', title: 'Nauru', phone: '674' },
  { id: 'NU', title: 'Niue', phone: '683' },
  { id: 'NZ', title: 'New Zealand', phone: '64' },
  { id: 'OM', title: 'Oman', phone: '968' },
  { id: 'PA', title: 'Panama', phone: '507' },
  { id: 'PE', title: 'Peru', phone: '51' },
  { id: 'PF', title: 'French Polynesia', phone: '689' },
  { id: 'PG', title: 'Papua New Guinea', phone: '675' },
  { id: 'PH', title: 'Philippines', phone: '63' },
  { id: 'PK', title: 'Pakistan', phone: '92' },
  { id: 'PL', title: 'Poland', phone: '48' },
  {
    id: 'PM',
    title: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { id: 'PN', title: 'Pitcairn', phone: '870' },
  { id: 'PR', title: 'Puerto Rico', phone: '1' },
  {
    id: 'PS',
    title: 'Palestine, State of',
    phone: '970',
  },
  { id: 'PT', title: 'Portugal', phone: '351' },
  { id: 'PW', title: 'Palau', phone: '680' },
  { id: 'PY', title: 'Paraguay', phone: '595' },
  { id: 'QA', title: 'Qatar', phone: '974' },
  { id: 'RE', title: 'Reunion', phone: '262' },
  { id: 'RO', title: 'Romania', phone: '40' },
  { id: 'RS', title: 'Serbia', phone: '381' },
  { id: 'RU', title: 'Russian Federation', phone: '7' },
  { id: 'RW', title: 'Rwanda', phone: '250' },
  { id: 'SA', title: 'Saudi Arabia', phone: '966' },
  { id: 'SB', title: 'Solomon Islands', phone: '677' },
  { id: 'SC', title: 'Seychelles', phone: '248' },
  { id: 'SD', title: 'Sudan', phone: '249' },
  { id: 'SE', title: 'Sweden', phone: '46' },
  { id: 'SG', title: 'Singapore', phone: '65' },
  { id: 'SH', title: 'Saint Helena', phone: '290' },
  { id: 'SI', title: 'Slovenia', phone: '386' },
  {
    id: 'SJ',
    title: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { id: 'SK', title: 'Slovakia', phone: '421' },
  { id: 'SL', title: 'Sierra Leone', phone: '232' },
  { id: 'SM', title: 'San Marino', phone: '378' },
  { id: 'SN', title: 'Senegal', phone: '221' },
  { id: 'SO', title: 'Somalia', phone: '252' },
  { id: 'SR', title: 'Suriname', phone: '597' },
  { id: 'SS', title: 'South Sudan', phone: '211' },
  {
    id: 'ST',
    title: 'Sao Tome and Principe',
    phone: '239',
  },
  { id: 'SV', title: 'El Salvador', phone: '503' },
  {
    id: 'SX',
    title: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    id: 'SY',
    title: 'Syrian Arab Republic',
    phone: '963',
  },
  { id: 'SZ', title: 'Swaziland', phone: '268' },
  {
    id: 'TC',
    title: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { id: 'TD', title: 'Chad', phone: '235' },
  {
    id: 'TF',
    title: 'French Southern Territories',
    phone: '262',
  },
  { id: 'TG', title: 'Togo', phone: '228' },
  { id: 'TH', title: 'Thailand', phone: '66' },
  { id: 'TJ', title: 'Tajikistan', phone: '992' },
  { id: 'TK', title: 'Tokelau', phone: '690' },
  { id: 'TL', title: 'Timor-Leste', phone: '670' },
  { id: 'TM', title: 'Turkmenistan', phone: '993' },
  { id: 'TN', title: 'Tunisia', phone: '216' },
  { id: 'TO', title: 'Tonga', phone: '676' },
  { id: 'TR', title: 'Turkey', phone: '90' },
  {
    id: 'TT',
    title: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { id: 'TV', title: 'Tuvalu', phone: '688' },
  {
    id: 'TW',
    title: 'Taiwan, Republic of China',
    phone: '886',
  },
  {
    id: 'TZ',
    title: 'United Republic of Tanzania',
    phone: '255',
  },
  { id: 'UA', title: 'Ukraine', phone: '380' },
  { id: 'UG', title: 'Uganda', phone: '256' },
  {
    id: 'US',
    title: 'United States',
    phone: '1',
    suggested: true,
  },
  { id: 'UY', title: 'Uruguay', phone: '598' },
  { id: 'UZ', title: 'Uzbekistan', phone: '998' },
  {
    id: 'VA',
    title: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    id: 'VC',
    title: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { id: 'VE', title: 'Venezuela', phone: '58' },
  {
    id: 'VG',
    title: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    id: 'VI',
    title: 'US Virgin Islands',
    phone: '1-340',
  },
  { id: 'VN', title: 'Vietnam', phone: '84' },
  { id: 'VU', title: 'Vanuatu', phone: '678' },
  { id: 'WF', title: 'Wallis and Futuna', phone: '681' },
  { id: 'WS', title: 'Samoa', phone: '685' },
  { id: 'XK', title: 'Kosovo', phone: '383' },
  { id: 'YE', title: 'Yemen', phone: '967' },
  { id: 'YT', title: 'Mayotte', phone: '262' },
  { id: 'ZA', title: 'South Africa', phone: '27' },
  { id: 'ZM', title: 'Zambia', phone: '260' },
  { id: 'ZW', title: 'Zimbabwe', phone: '263' },
];
